Import Debian version 9.0.2+parrot0
desktop-base (9.0.2+parrot0) testing; urgency=medium

  * Import new Debian release

desktop-base (9.0.2) unstable; urgency=medium

  [ Aurélien COUDERC ]
  * Include size 3840x2160 (4k) wallpaper and lockscreen. (Closes: #851930)
  * Include more sizes of emblem-debian, add emblem-debian-white.
    (Closes: #833529)
  * Lockscreen/Joy: fix wallpaper image being used instead of lockscreen.

desktop-base (9.0.1) unstable; urgency=medium

  [ Aurélien COUDERC ]
  * postinst: Report success even when update-grub fails, this is needed
    for installation to work inside live systems. (Closes: #850601)
  * Plymouth/{softWaves,Lines,Joy}: provide fsckd progress support. Thanks to
    Ubuntu and Didier Roche for doing the work and providing timely info.
    (Closes: #850181)
  * Plymouth/softWaves: various visual tweaks, boost logo glow, improvements
    in password input rendering. Thanks Juliette!
  * Plymouth/Lines: ensure password field doesn’t bump into the Debian image
    even for smaller height screens. (Closes: #774226)
  * Plymouth/Lines: Remove 8 from Debian8 assets.

desktop-base (9.0.0) unstable; urgency=medium

  [ Aurélien COUDERC ]
  * Implement Plymouth splash for Stretch’s soft Waves theme.
    (Closes: #843998, #842078)
  * Prepare for plymouth splash integration into theme packs that will allow
    splash selection via alternatives in the future.
  * Fix postinst broken in 9.0.0~exp2 on install (and not upgrade) of the
    package.
  * Added myself to the uploaders.

desktop-base (9.0.0~exp2) experimental; urgency=medium

  [ Aurélien COUDERC ]
  * Fix detection of update-initramfs. (Closes: #843727)
  * Include GRUB text/background colors in the theme pack / alternatives
    system. (Closes: #606383)

  * Additional wallpaper and lockscreen ratios for Soft Waves theme.
  * Remove Moreblue theme from Lenny.
  * Add theme pack support Joy/Spacefun themes.

  * Use dash instead of bash for postinst
  * Generate all GRUB bitmaps from SVG at build time instead of versioning
    them.
  * Stop shipping SDDM breeze-based theme, now in plasma-workspace.

desktop-base (9.0.0~exp1) experimental; urgency=medium

  [ Aurélien COUDERC ]
  * Initial support for Soft Waves theme by Juliette Belin.
    - Default theme for GRUB (Closes: #598776, #773369)
    - Default theme for Gnome wallpaper and lock screen
    - Default theme for Plasma 5 wallpaper (Closes: #831730)
    - Theme available for SDDM login and lock screen
    - debian/copyright updated
  * Initial support for global theme switching via alternatives

  * Remove references to long gone KDE3 globals in maintainer scripts.
    (Closes: #659549)
  * README.Debian: inform about updating initrds too. (Closes: #612163)
  * Document use of sync use before grub update in postinst. (Closes: #611364)
  * Add SDDM theming for KDE/Plasma 5:
    - Based on default SDDM theme breeze + Debian theme background.
    - Can be configured with alternatives (also works in lightdm).
   (Closes: #415064, #608523, #611170, #670866, #762276)
  * Remove deprecated ksplash and kdm from KDE4. (Closes: #607842)
  * Remove deprecated splash options from Gnome 2.
  * Some cleanup in maintainer scripts to correctly handle alternatives.
    (Closes: #773404)

  * Fix lintian warning command-with-path-in-maintainer-script in
    postinst script.
  * Bump Standards-Version to 3.9.8 (no changes needed).

  [ Yves-Alexis Perez ]
  * Also use Debian wallpaper for second monitor on Xfce.       closes: #785371

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,108 +1,227 @@
-#!/bin/bash -e
+#!/bin/sh
 set -e
 
+# Tag to allow some debhelper commands to inject relevant code
 #DEBHELPER#
 
-if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
-  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
+if [ "${1}" = "configure" ] && [ ! -z "${2}" ]; then
+    if dpkg --compare-versions ${2} le "9.0.0~exp1"; then
+        # Try remove folder if empty, left after 9.0.0~exp1 conf suppression
+        # by debhelper conffile handling
+        OLD_KDM_DIR=/etc/default/kdm.d
+        if [ -d ${OLD_KDM_DIR} ] ; then
+            echo "Removing old KDM configuration directory \"${OLD_KDM_DIR}\""
+            rmdir ${OLD_KDM_DIR} || true
+        fi
+    fi
 fi
 
-if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 7; then
-  update-alternatives --remove desktop-grub /usr/share/images/desktop-base/moreblue-orbit-grub.png
-fi
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ]; then
+    # Theme package alternatives
+    while read theme priority; do
+        update-alternatives --install \
+            /usr/share/desktop-base/active-theme \
+            desktop-theme \
+            /usr/share/desktop-base/$theme-theme $priority
+    done << EOF
+parrot 60
+softwaves 50
+lines 40
+joy 30
+joy-inksplat 30
+spacefun 30
+EOF
 
-if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
-    # Alternatives for the background
-    while read background priority; do
+    # Use active theme as highest priority for background
+    update-alternatives --install \
+        /usr/share/images/desktop-base/desktop-background \
+        desktop-background \
+        /usr/share/desktop-base/active-theme/wallpaper/contents/images/1920x1080.svg 70
+    # Alternatives for the background in theme packages
+    while read theme filename priority; do
         update-alternatives --install \
             /usr/share/images/desktop-base/desktop-background \
             desktop-background \
-            /usr/share/images/desktop-base/$background $priority
+            /usr/share/desktop-base/$theme-theme/wallpaper/contents/images/$filename $priority
     done << EOF
-parrot-wallpaper_1024x768.png 70
-parrot-wallpaper_1600x1200.png 70
-parrot-wallpaper_1280x1024.png 70
-parrot-wallpaper_1280x800.png 70
-parrot-wallpaper_1920x1080.png 75
-parrot-wallpaper_1920x1200.png 70
-lines-wallpaper_1280x1024.svg 60
-lines-wallpaper_1600x1200.svg 60
-lines-wallpaper_1920x1080.svg 65
-lines-wallpaper_1920x1200.svg 60
-lines-wallpaper_2560x1080.svg 60
-joy-wallpaper_1600x1200.svg 55
-joy-wallpaper_1280x1024.svg 55
-joy-wallpaper_1920x1080.svg 55
-joy-wallpaper_1920x1200.svg 55
-joy-inksplat-wallpaper_1920x1080.svg 55
-spacefun-wallpaper.svg 50
-spacefun-wallpaper-widescreen.svg  50
-moreblue-orbit-wallpaper.svg 40
-moreblue-orbit-wallpaper-widescreen.svg 40
+parrot 1024x768.png 67
+parrot 1600x1200.png 67
+parrot 1280x1024.png 67
+parrot 1280x800.png 67
+parrot 1920x1080.png 67
+parrot 1920x1200.png 67
+softwaves 1024x768.svg 65
+softwaves 1280x720.svg 65
+softwaves 1280x800.svg 65
+softwaves 1280x1024.svg 65
+softwaves 1600x1200.svg 65
+softwaves 1920x1080.svg 65
+softwaves 1920x1200.svg 65
+softwaves 2560x1440.svg 65
+softwaves 2560x1600.svg 65
+lines 1280x1024.svg 60
+lines 1600x1200.svg 60
+lines 1920x1080.svg 60
+lines 1920x1200.svg 60
+lines 2560x1080.svg 60
+joy 1280x720.svg 50
+joy 1280x1024.svg 50
+joy 1600x1200.svg 50
+joy 1920x1080.svg 50
+joy 1920x1200.svg 50
+joy-inksplat 1280x720.svg 50
+joy-inksplat 1280x1024.svg 50
+joy-inksplat 1600x1200.svg 50
+joy-inksplat 1920x1080.svg 50
+joy-inksplat 1920x1200.svg 50
+spacefun 1280x720.svg 50
+spacefun 1280x1024.svg 50
+spacefun 1920x1080.svg 50
+spacefun 1920x1200.svg 50
 EOF
 
     # Set up an alternative for the XML version of the background
     # (for GNOME)
-    while read desktopbackground priority; do
+    # Highest priority for active theme
+    update-alternatives --install \
+        /usr/share/images/desktop-base/desktop-background.xml \
+        desktop-background.xml \
+        /usr/share/desktop-base/active-theme/wallpaper/gnome-background.xml 50
+    # Alternatives for theme packages
+    while read theme priority; do
         update-alternatives --install \
             /usr/share/images/desktop-base/desktop-background.xml \
             desktop-background.xml \
-            /usr/share/images/desktop-base/$desktopbackground $priority
+            /usr/share/desktop-base/$theme-theme/wallpaper/gnome-background.xml $priority
     done << EOF
-parrot.xml 30
-lines.xml 20
-joy.xml 10
+parrot 45
+softwaves 40
+lines 30
+joy 20
+joy-inksplat 20
+spacefun 20
 EOF
 
-    # Alternatives for the splash
-    while read splash priority; do
+    # Set up an alternative for the XML version of the lock screen
+    # (for GNOME)
+    # Highest priority for active theme
+    update-alternatives --install \
+        /usr/share/images/desktop-base/desktop-lockscreen.xml \
+        desktop-lockscreen.xml \
+        /usr/share/desktop-base/active-theme/lockscreen/gnome-background.xml 50
+    # Alternatives for theme packages
+    while read theme priority; do
         update-alternatives --install \
-            /usr/share/images/desktop-base/desktop-splash \
-            desktop-splash \
-            /usr/share/images/desktop-base/$splash $priority
+            /usr/share/images/desktop-base/desktop-lockscreen.xml \
+            desktop-lockscreen.xml \
+            /usr/share/desktop-base/$theme-theme/lockscreen/gnome-background.xml $priority
     done << EOF
-spacefun-splash.svg 50
-moreblue-orbit-splash.png 40
+parrot 45
+softwaves 40
+lines 30
+joy 20
+spacefun 20
 EOF
 
-    # Alternatives for grub
+    # Set up an alternative for the wallpaper for Plasma 5/KDE
+    # Highest priority for active theme
+    update-alternatives --install \
+        /usr/share/wallpapers/DebianTheme \
+        desktop-plasma5-wallpaper \
+        /usr/share/desktop-base/active-theme/wallpaper 50
+    # Alternatives for theme packages
+    while read theme priority; do
+        update-alternatives --install \
+            /usr/share/wallpapers/DebianTheme \
+            desktop-plasma5-wallpaper \
+            /usr/share/desktop-base/$theme-theme/wallpaper $priority
+    done << EOF
+parrot 45
+softwaves 40
+lines 30
+joy 20
+joy-inksplat 20
+spacefun 20
+EOF
+
+    # Login theme
+    # Highest priority for active theme
+    update-alternatives --install /usr/share/images/desktop-base/login-background.svg \
+        desktop-login-background \
+        /usr/share/desktop-base/active-theme/login/background.svg 50
+    # Alternatives for theme packages
+    while read theme background priority; do
+        update-alternatives --install /usr/share/images/desktop-base/login-background.svg \
+            desktop-login-background \
+            /usr/share/desktop-base/$theme-theme/login/$background $priority
+    done << EOF
+parrot background.jpg 45
+softwaves background.svg 40
+lines background.svg 30
+lines background-nologo.svg 30
+joy background.svg 20
+spacefun background.svg 20
+EOF
+
+    # Set up an alternative for the GRUB background/colors config
+    # Highest priority for active theme
     ## Favor widescreen / hi-res background for efi installations
-    num_grub_efi_installed=$(dpkg-query --list "grub-efi*" | grep "^i" | wc -l)
+    num_grub_efi_installed=$(dpkg-query --list "grub-efi*" 2> /dev/null | grep "^i" | wc -l)
     if [ $num_grub_efi_installed -gt 0 ] ; then
-        lines_grub_prio=15
-        lines_grub_1920_prio=20
+        grub_first_ratio="16x9"
+        grub_second_ratio="4x3"
     else
-        lines_grub_prio=20
-        lines_grub_1920_prio=15
+        grub_first_ratio="4x3"
+        grub_second_ratio="16x9"
     fi
     update-alternatives --install \
         /usr/share/images/desktop-base/desktop-grub.png \
         desktop-grub \
-        /usr/share/images/desktop-base/lines-grub.png $lines_grub_prio
+        /usr/share/desktop-base/active-theme/grub/grub-${grub_first_ratio}.png 50 \
+        --slave /usr/share/desktop-base/grub_background.sh \
+        desktop-grub.sh \
+        /usr/share/desktop-base/active-theme/grub/grub_background.sh
     update-alternatives --install \
         /usr/share/images/desktop-base/desktop-grub.png \
         desktop-grub \
-        /usr/share/images/desktop-base/lines-grub-1920x1080.png $lines_grub_1920_prio
-
-    while read background priority; do
-        update-alternatives --install \
-            /usr/share/images/desktop-base/desktop-grub.png \
+        /usr/share/desktop-base/active-theme/grub/grub-${grub_second_ratio}.png 45 \
+        --slave /usr/share/desktop-base/grub_background.sh \
+        desktop-grub.sh \
+        /usr/share/desktop-base/active-theme/grub/grub_background.sh
+    # Alternatives for theme packages
+    while read theme ratio priority; do
+        update-alternatives --install /usr/share/images/desktop-base/desktop-grub.png \
             desktop-grub \
-            /usr/share/images/desktop-base/$background $priority
+            /usr/share/desktop-base/$theme-theme/grub/grub-$ratio.png $priority \
+            --slave /usr/share/desktop-base/grub_background.sh \
+            desktop-grub.sh \
+            /usr/share/desktop-base/$theme-theme/grub/grub_background.sh
     done << EOF
-parrot-grub.png 25
-joy-grub.png 15
-spacefun-grub.png 15
-spacefun-grub-widescreen.png 14
+parrot 4x3 45
+parrot 16x9 45
+softwaves 4x3 40
+softwaves 16x9 40
+lines 4x3 30
+lines 16x9 30
+joy 4x3 30
+joy 16x9 30
+spacefun 4x3 30
+spacefun 16x9 30
 EOF
 
-    # GRUB background
-    if which update-grub2 > /dev/null ; then
+    # Apply GRUB background update into /boot
+    if which update-grub > /dev/null ; then
+        # Ensure the background image file has actually been written to disc
+        # before updating.
         sync
-        update-grub2 || true
+        # Report success whatever grub return status. This is needed at least
+        # in live systems fon installation to succeed (see #850601).
+        # Until we find a better solution like detecting we’re in a live image
+        # and not calling update-grub at all.
+        update-grub || echo "Updating grub failed, report success anyway!"
     fi
 
-    if [ -x /usr/sbin/update-initramfs ]; then
+    if which update-initramfs > /dev/null; then
         update-initramfs -u
     fi
 
